# Generated by Django 4.1.2 on 2023-05-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_delete_tip_remove_plant_qr_code1_delete_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='this_year',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
